// Board: robotweb-esp32s3-st7789
// Generated by Robotweb Component Lab
// Hardware: ESP32-S3 N16R8 + ST7789 240x320 + 2x Motor DC L298N

#include "board.h"
#include "mcp_server.h"
#include "esp_log.h"
#include "driver/gpio.h"
#include "driver/ledc.h"
#include <string>

// === Motor DC L298N ===
#define MOTOR_IN1 6
#define MOTOR_IN2 7
#define MOTOR_IN3 8
#define MOTOR_IN4 9
#define MOTOR_ENA 10
#define MOTOR_ENB 11

static const char* TAG_MOTOR = "MOTOR";

static void motor_set_speed_impl(uint8_t a, uint8_t b) {
    ledc_set_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0, a);
    ledc_update_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0);
    ledc_set_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_1, b);
    ledc_update_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_1);
}
static void motor_forward_impl(int s)  { gpio_set_level(MOTOR_IN1,1); gpio_set_level(MOTOR_IN2,0); gpio_set_level(MOTOR_IN3,1); gpio_set_level(MOTOR_IN4,0); motor_set_speed_impl(s,s); ESP_LOGI(TAG_MOTOR,"Forward %d",s); }
static void motor_backward_impl(int s) { gpio_set_level(MOTOR_IN1,0); gpio_set_level(MOTOR_IN2,1); gpio_set_level(MOTOR_IN3,0); gpio_set_level(MOTOR_IN4,1); motor_set_speed_impl(s,s); ESP_LOGI(TAG_MOTOR,"Backward %d",s); }
static void motor_left_impl(int s)     { gpio_set_level(MOTOR_IN1,0); gpio_set_level(MOTOR_IN2,1); gpio_set_level(MOTOR_IN3,1); gpio_set_level(MOTOR_IN4,0); motor_set_speed_impl(s,s); }
static void motor_right_impl(int s)    { gpio_set_level(MOTOR_IN1,1); gpio_set_level(MOTOR_IN2,0); gpio_set_level(MOTOR_IN3,0); gpio_set_level(MOTOR_IN4,1); motor_set_speed_impl(s,s); }
static void motor_stop_impl()          { gpio_set_level(MOTOR_IN1,0); gpio_set_level(MOTOR_IN2,0); gpio_set_level(MOTOR_IN3,0); gpio_set_level(MOTOR_IN4,0); motor_set_speed_impl(0,0); ESP_LOGI(TAG_MOTOR,"Stop"); }

static void motor_dc_init() {
    gpio_config_t c = {
        .pin_bit_mask=(1ULL<<MOTOR_IN1)|(1ULL<<MOTOR_IN2)|(1ULL<<MOTOR_IN3)|(1ULL<<MOTOR_IN4),
        .mode=GPIO_MODE_OUTPUT, .pull_up_en=GPIO_PULLUP_DISABLE,
        .pull_down_en=GPIO_PULLDOWN_DISABLE, .intr_type=GPIO_INTR_DISABLE
    };
    gpio_config(&c);
    ledc_timer_config_t t = {.speed_mode=LEDC_LOW_SPEED_MODE, .duty_resolution=LEDC_TIMER_8_BIT,
        .timer_num=LEDC_TIMER_0, .freq_hz=1000, .clk_cfg=LEDC_AUTO_CLK};
    ledc_timer_config(&t);
    ledc_channel_config_t ca = {.gpio_num=MOTOR_ENA, .speed_mode=LEDC_LOW_SPEED_MODE,
        .channel=LEDC_CHANNEL_0, .timer_sel=LEDC_TIMER_0, .duty=0, .hpoint=0};
    ledc_channel_config(&ca);
    ledc_channel_config_t cb = {.gpio_num=MOTOR_ENB, .speed_mode=LEDC_LOW_SPEED_MODE,
        .channel=LEDC_CHANNEL_1, .timer_sel=LEDC_TIMER_0, .duty=0, .hpoint=0};
    ledc_channel_config(&cb);
    motor_stop_impl();
    ESP_LOGI(TAG_MOTOR, "Motor DC init OK. IN1=%d IN2=%d IN3=%d IN4=%d ENA=%d ENB=%d",
             MOTOR_IN1,MOTOR_IN2,MOTOR_IN3,MOTOR_IN4,MOTOR_ENA,MOTOR_ENB);
}

class RobowebEsp32s3St7789Board : public Board {
public:
    void Initialize() override {
        ESP_LOGI("BOARD", "=== robotweb-esp32s3-st7789 initializing ===");
        motor_dc_init();
        Board::Initialize();
        ESP_LOGI("BOARD", "=== Board ready ===");
    }

    void InitializeTools() override {
        auto& mcp = McpServer::GetInstance();

        mcp.AddTool(
            "self.motor.move",
            "Control robot movement. Direction: forward, backward, left, right, stop.",
            PropertyList({Property("direction", kPropertyTypeString)}),
            [](const PropertyList& props) -> ReturnValue {
                std::string dir = props["direction"].value<std::string>();
                if      (dir == "forward")  motor_forward_impl(200);
                else if (dir == "backward") motor_backward_impl(200);
                else if (dir == "left")     motor_left_impl(150);
                else if (dir == "right")    motor_right_impl(150);
                else                        motor_stop_impl();
                return true;
            }
        );

        mcp.AddTool(
            "self.motor.stop",
            "Stop all motors immediately.",
            PropertyList(),
            [](const PropertyList& props) -> ReturnValue {
                motor_stop_impl();
                return true;
            }
        );

        mcp.AddTool(
            "self.motor.speed",
            "Set motor speed from 0 to 255.",
            PropertyList({Property("speed", kPropertyTypeInteger, 0, 255)}),
            [](const PropertyList& props) -> ReturnValue {
                int spd = props["speed"].value<int>();
                motor_set_speed_impl(spd, spd);
                return true;
            }
        );
    }
};

DECLARE_BOARD(RobowebEsp32s3St7789Board);